// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Opsi konfigurasi default [FirebaseOptions] untuk menghubungkan aplikasi Flutter
/// dengan proyek Firebase berdasarkan target platform (Web, Android, iOS, dll).
///
/// Contoh Penggunaan:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Mengembalikan konfigurasi [FirebaseOptions] yang sesuai dengan platform target saat runtime.
  static FirebaseOptions get currentPlatform {

    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ0uYv724b_bonuk2ETFhdx8STzhJe1og',
    appId: '1:737817094016:web:c6ff75e72cce901bf3c365',
    messagingSenderId: '737817094016',
    projectId: 'ppkd-b7-project',
    authDomain: 'ppkd-b7-project.firebaseapp.com',
    storageBucket: 'ppkd-b7-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2772xBrQkv4gvEUTUtceKt_ZinU2VYhA',
    appId: '1:737817094016:android:aa186ea12d3c4f0ff3c365',
    messagingSenderId: '737817094016',
    projectId: 'ppkd-b7-project',
    storageBucket: 'ppkd-b7-project.firebasestorage.app',
  );
}
